# Generated by Django 4.2.9 on 2024-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_age_userinfo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
