# Generated by Django 4.2.9 on 2024-01-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_remove_userinfo_data_remove_userinfo_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
    ]
